[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "notetree"
version = "1.0"
readme = "README.md"
license = "GPL-3.0-only"
license-files = [
    "LICENSE",
    "THIRD_PARTY_NOTICES.md",
    "icons/fontawesome/LICENSE.txt"
]
requires-python = ">=3.10"

dependencies = [
    "PyQt6",
]

[project.gui-scripts]
notetree = "notetree.app:main"

[tool.setuptools.packages.find]
include = ["notetree*"]
